version: '3'

services:
    db:
        image: postgres:16
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        ports:
            - "5454:5432"
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=root
            - POSTGRES_USER=arina
            - POSTGRES_DB=api
